### ISSUE TITLE
Doctor's registration

### ISSUE THREAD

**Issue by peterkiptoo** [amankumar367/Hospital-Appointy-Android#1]
No interface for registering new doctor

**Comment by amankumar367** [comment]
@peterkiptoo Sorry for the late reply.

> Doctor registration will be done through the [Hospital-Appointy-Web](https://github.com/amankumar367/Hospital-Appointy-Web) & you can see web demo here [Click Here](https://amankumar367.github.io/Hospital-Appointy-Web/)

> Doctor registeration can login from app or web, only when his account approved by the Manager & same for the Manager, his account will be approved by the admin.

**Comment by peterkiptoo** [comment]
Thank you, And if I may ask for a favour, could you please assist me with a
screenshot of the firebase db structure?

**Comment by amankumar367** [comment]
@peterkiptoo PFA

> Please check the below attatchment

[Aman-hospital-appointy.txt](https://github.com/amankumar367/Hospital-Appointy-Android/files/4648153/Aman-hospital-appointy.txt)

**Comment by peterkiptoo** [comment]
Thank you so much
