### ISSUE TITLE
Firebase Data

### ISSUE THREAD

**Issue by KinWei1** [amankumar367/Hospital-Appointy-Android#3]
Hi can you show the data on your firebase database?

**Comment by bokiri1306** [comment]
Hi can you show the data on your firebase database?

**Comment by amankumar367** [comment]
@KinWei1 @bokiri1306, Please find the attachment for the firebase DB structure
[Aman-hospital-appointy.txt](https://github.com/amankumar367/Hospital-Appointy-Android/files/5791678/Aman-hospital-appointy.txt)
