### ISSUE TITLE
Firebase and Code Issue

### ISSUE THREAD

**Issue by adisaj98** [amankumar367/Hospital-Appointy-Android#4]
Hi Aman, I am getting this error 
java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
in the onStart() of the Patient_BookAppointment class for this mDataBaseRef.child(getIntent().getStringExtra("DoctorUserId").toString()).addValueEventListener(new ValueEventListener()

Any Idea whats wrong?

**Comment by adisaj98** [comment]
Also I dont see a DoctorUserId and a UserId in your database that you have attached in the github, I only see a Doctor_ID and PatientID

**Comment by amankumar367** [comment]
This has been resolved in #6
